### ISSUE TITLE
Add compatibility with oil from cargo ships

### ISSUE THREAD

**Issue by ZXQWAS** [StephanSteinert/steinios_unlasting_oil#1]
Could you add compatibility with deep sea oil from https://mods.factorio.com/mod/cargo-ships please? I installed it and only land oil is finite, while deep sea oil are infinite.

**Comment by StephanSteinert** [comment]
Hi,

it was easier as i remembered the last time i tried it.
Added it now.

Cu, Stephan

**Comment by ZXQWAS** [comment]
Wow this was fast.
