### ISSUE TITLE
Wrong multiplier for Cargo Ships oil?

### ISSUE THREAD

**Issue by ZXQWAS** [StephanSteinert/steinios_unlasting_oil#2]
I only now got to make an oil rig. The amount of available resources looks to be 10 times what is expected, check screenshot. I have the default "1" in all mod settings.
https://i.imgur.com/BvSCRGy.png (Ignore all other stats lol.)
Maybe I misunderstand something though?

**Comment by StephanSteinert** [comment]
Hi,

it's based on the internal game mechanics.
https://forums.factorio.com/viewtopic.php?f=23&t=47577

Cu, steino / Stephan
